name: 'Checkout the bitnami repo and build images'
on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |

          # Checkout the repository
          echo "*** Configuring the local git ***"
          git config --global user.email "repo-bitnami-docker-wordpress-nginx@wordlift.io"
          git config --global user.name "wordlift-bot"
          git config --global advice.detachedHead false

          ## Checkout the tags
          echo "*** Cloning the original bitnami/bitnami-docker-wordpress-nginx repo ***"
          git clone https://github.com/bitnami/bitnami-docker-wordpress-nginx.git
          cd bitnami-docker-wordpress-nginx

          # Build the images
          echo ${{ secrets.GITHUB_TOKEN }} | docker login --username ${{ github.repository_owner }} --password-stdin ghcr.io

          tags=$(git describe --tags $(git rev-list --tags --after=$(date -d '-1 day' '+%s')))
          for tag in $tags; do
              echo "*** Checking out tag $tag ***"
              git checkout $tag

              # Apply the patch
              echo "*** Applying patch ***"
              curl -s https://gist.githubusercontent.com/ziodave/20ab49f5ea2e6e500255c7e5ff1fd5e2/raw/e820c925f07ec26bdb6e87353d142a1d3445d7d3/1.patch | git apply -

              echo "*** Preparing tags ***"
              version=$(echo $tag | cut -d '-' -f1)
              echo "*** Version: $version ***"
              os=$(echo $tag | cut -d '-' -f2)
              echo "*** OS: $os ***"
              osrel=$(echo $tag | cut -d '-' -f3)
              echo "*** OS Rel: $osrel ***"
              # Ex: 6
              tag0="${{ github.repository }}$(echo $version | grep -Eo '^(\d+)')"
              echo "*** Tag 0: $tag0 ***"
              # Ex: 6-debian-11
              tag1="${{ github.repository }}$tag0-$os-$osrel"
              echo "*** Tag 1: $tag1 ***"
              # Ex: 6.0.0
              tag2="${{ github.repository }}$version"
              echo "*** Tag 2: $tag2 ***"
              # Ex: 6.0.0-debian-11-r0
              tag3="${{ github.repository }}$tag"
              echo "*** Tag 3: $tag3 ***"
              
              ## Tag the images
              echo "*** Building image with tags $tag0, $tag1, $tag2 and $tag3 ***"
              docker build . -t $tag0 -t $tag1 -t $tag2 -t $tag3
          done

