name: 'Discover new tags and build images'
on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
        
          # Checkout the repository
          echo "*** Configuring the local git ***"
          git config --global user.email "repo-bitnami-docker-wordpress-nginx@wordlift.io"
          git config --global user.name "wordlift-bot"

          ## Checkout the tags
          echo "*** Cloning the original bitnami/bitnami-docker-wordpress-nginx repo ***"
          git clone https://github.com/bitnami/bitnami-docker-wordpress-nginx.git
          cd bitnami-docker-wordpress-nginx

          # Build the images
          echo ${{ secrets.GITHUB_TOKEN }} | docker login --username ${{ github.repository_owner }} --password-stdin ghcr.io

          tags=$(git describe --tags $(git rev-list --tags --after=$(date -d '-1 day' '+%s')))
          for tag in $tags; do
              echo "*** Checking out tag $tag ***"
              git checkout $tag

              # Apply the patch
              curl -s https://gist.githubusercontent.com/ziodave/20ab49f5ea2e6e500255c7e5ff1fd5e2/raw/e820c925f07ec26bdb6e87353d142a1d3445d7d3/1.patch | git apply -


              tag_0="${{ github.repository }}$(echo $tag | pcregrep -o1 '^(\d+)')"
              tag_1="${{ github.repository }}$(echo $tag | pcregrep -o1 -o2 '^(\d+)\.\d+\.\d+(-\w+-\d+)')"
              tag_2="${{ github.repository }}$(echo $tag | pcregrep -o1 '^(\d+\.\d+\.\d+)')"
              tag_3="${{ github.repository }}$tag"
              
              tags_switches="-t ${{ github.repository }}$(echo $tag | pcregrep --om-separator=' -t ${{ github.repository }}' -o5 -o4 -o3 -o2 -o1 '^((\d+)\.\d+\.\d+)?(-\w+-\d+).*$' -)"

              ## Tag the images
              echo "*** Building image with tags $tag_0, $tag_1, $tag_2 and $tag_3 ***"
              docker build . -t $tag_0 -t $tag_1 -t $tag_2 -t $tag_3
          done
